events {
    worker_connections 1024;
}

http {
    include         /etc/nginx/mime.types;
    default_type    application/octet-stream;

    # DevSecOps Hardening: скрываем версию сервера
    server_tokens off;

    server {
        listen 80;
        server_name localhost;

        location / {
            root    /usr/share/nginx/html;
            index   index.html;
        }

        # Перехват ошибки 404
        error_page 404 /404.html;

        # Правило отдачи страницы ошибки
        location = /404.html {
            root /usr/share/nginx/html;
            internal; # DevSecOps: запрещает прямой доступ к файлу по URL /404.html
        }
    }
}